-- Database: postgres

-- DROP DATABASE IF EXISTS postgres;

CREATE DATABASE postgres
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_World.1252'
    LC_CTYPE = 'English_World.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- SCHEMA: movie_theater

-- DROP SCHEMA IF EXISTS movie_theater ;

CREATE SCHEMA IF NOT EXISTS movie_theater
    AUTHORIZATION postgres;
	
-- Table: movie_theater.user

-- DROP TABLE IF EXISTS movie_theater."user";

CREATE TABLE IF NOT EXISTS movie_theater."user"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_name character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    full_name character varying COLLATE pg_catalog."default" NOT NULL,
    enabled boolean,
    role character varying COLLATE pg_catalog."default",
    CONSTRAINT user_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS movie_theater."user"
    OWNER to postgres;
	
-- SEQUENCE: movie_theater.user_id_seq

-- DROP SEQUENCE IF EXISTS movie_theater.user_id_seq;

CREATE SEQUENCE IF NOT EXISTS movie_theater.user_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE movie_theater.user_id_seq
    OWNER TO postgres;
	
INSERT INTO movie_theater.user(
	 user_name, password, email, full_name, enabled, role)
	VALUES ('admin','$2a$10$.iot6V2kegRp6Qow811HYuIAJ6jo383jgdTqSQiHhZUI46mYovZum','drors96@gmail.com','master.D',True,'ADMIN');

-- Table: movie_theater.films

-- DROP TABLE IF EXISTS movie_theater.films;

CREATE TABLE IF NOT EXISTS movie_theater.films
(
    id integer NOT NULL DEFAULT nextval('movie_theater.movies_id_seq'::regclass),
    author character varying COLLATE pg_catalog."default",
    show_time timestamp without time zone,
    show_hide_film boolean,
    image_path character varying COLLATE pg_catalog."default",
    volumn_film integer,
    description character varying COLLATE pg_catalog."default",
    name character varying COLLATE pg_catalog."default" NOT NULL,
    production_time bigint,
    type character varying COLLATE pg_catalog."default",
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    enabled boolean,
    CONSTRAINT movies_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS movie_theater.films
    OWNER to postgres;